//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.13 at 04:05:44 PM CET 
//


package systemlogic.businesslogicservices.dto.person;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the systemlogic.businesslogicservices.dto.person package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: systemlogic.businesslogicservices.dto.person
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPerson() {
        return new PersonDto();
    }

    /**
     * Create an instance of {@link PersonDto.HealthProfile }
     * 
     */
    public PersonDto.HealthProfile createPersonHealthProfile() {
        return new PersonDto.HealthProfile();
    }

    /**
     * Create an instance of {@link PersonDto.HealthProfile.MeasureType }
     * 
     */
    public PersonDto.HealthProfile.MeasureType createPersonHealthProfileMeasureType() {
        return new PersonDto.HealthProfile.MeasureType();
    }

}
